// <auto-generated />
using System;
using BangLuong.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BangLuong.Migrations
{
    [DbContext(typeof(BangLuongDbContext))]
    [Migration("20251107042337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BangLuong.Data.Entities.ChucVu", b =>
                {
                    b.Property<string>("MaCV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCV");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("BangLuong.Data.Entities.HopDong", b =>
                {
                    b.Property<int>("MaHD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHD"));

                    b.Property<string>("LoaiHD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LuongCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PhuCapAnTrua")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PhuCapDienThoai")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PhuCapKhac")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PhuCapTrachNhiem")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PhuCapXangXe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SoHopDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHD");

                    b.HasIndex("MaNV");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("BangLuong.Data.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaCV")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaPB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoanNganHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNganHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaCV");

                    b.HasIndex("MaPB");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("BangLuong.Data.Entities.PhongBan", b =>
                {
                    b.Property<string>("MaPB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPB");

                    b.ToTable("PhongBan");
                });

            modelBuilder.Entity("BangTinhLuong", b =>
                {
                    b.Property<int>("MaBL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBL"));

                    b.Property<decimal?>("GiamTruBHTN")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiamTruBHXH")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiamTruBHYT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiamTruThueTNCN")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KyLuongNam")
                        .HasColumnType("int");

                    b.Property<int>("KyLuongThang")
                        .HasColumnType("int");

                    b.Property<decimal>("LuongCoBan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LuongTangCa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("ThucLanh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongGiamTruKyLuat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongKhenThuong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongPhuCap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongThuNhap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBL");

                    b.HasIndex("MaNV");

                    b.ToTable("BangTinhLuong");
                });

            modelBuilder.Entity("ChamCong", b =>
                {
                    b.Property<int>("MaCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCC"));

                    b.Property<TimeSpan?>("GioRa")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("GioVao")
                        .HasColumnType("time");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("NgayChamCong")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SoGioTangCa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaCC");

                    b.HasIndex("MaNV");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("ChiTietKhenThuong", b =>
                {
                    b.Property<int>("MaCTKT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTKT"));

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("NgayKhenThuong")
                        .HasColumnType("datetime2");

                    b.HasKey("MaCTKT");

                    b.HasIndex("MaKT");

                    b.HasIndex("MaNV");

                    b.ToTable("ChiTietKhenThuong");
                });

            modelBuilder.Entity("ChiTietKyLuat", b =>
                {
                    b.Property<int>("MaCTKL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTKL"));

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKL")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("NgayViPham")
                        .HasColumnType("datetime2");

                    b.HasKey("MaCTKL");

                    b.HasIndex("MaKL");

                    b.HasIndex("MaNV");

                    b.ToTable("ChiTietKyLuat");
                });

            modelBuilder.Entity("ChiTietPhuCap", b =>
                {
                    b.Property<int>("MaCTPC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCTPC"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MaPC")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.HasKey("MaCTPC");

                    b.HasIndex("MaNV");

                    b.HasIndex("MaPC");

                    b.ToTable("ChiTietPhuCap");
                });

            modelBuilder.Entity("DanhMucKhenThuong", b =>
                {
                    b.Property<string>("MaKT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenKhenThuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKT");

                    b.ToTable("DanhMucKhenThuong");
                });

            modelBuilder.Entity("DanhMucKyLuat", b =>
                {
                    b.Property<string>("MaKL")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SoTienPhat")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenKyLuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKL");

                    b.ToTable("DanhMucKyLuat");
                });

            modelBuilder.Entity("DanhMucPhuCap", b =>
                {
                    b.Property<string>("MaPC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SoTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenPhuCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPC");

                    b.ToTable("DanhMucPhuCap");
                });

            modelBuilder.Entity("NguoiDung", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhanQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNV");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("NguoiPhuThuoc", b =>
                {
                    b.Property<int>("MaNPT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNPT"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MoiQuanHe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianBatDauGiamTru")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThucGiamTru")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNPT");

                    b.HasIndex("MaNV");

                    b.ToTable("NguoiPhuThuoc");
                });

            modelBuilder.Entity("ThamSoHeThong", b =>
                {
                    b.Property<string>("MaTS")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayApDung")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenThamSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTS");

                    b.ToTable("ThamSoHeThong");
                });

            modelBuilder.Entity("TongHopCong", b =>
                {
                    b.Property<int>("MaTHC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTHC"));

                    b.Property<int>("KyLuongNam")
                        .HasColumnType("int");

                    b.Property<int>("KyLuongThang")
                        .HasColumnType("int");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("SoGioTangCaCuoiTuan")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SoGioTangCaNgayLe")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SoGioTangCaNgayThuong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoNgayCong")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SoNgayNghiPhep")
                        .HasColumnType("int");

                    b.HasKey("MaTHC");

                    b.HasIndex("MaNV");

                    b.ToTable("TongHopCong");
                });

            modelBuilder.Entity("BangLuong.Data.Entities.HopDong", b =>
                {
                    b.HasOne("BangLuong.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("HopDong")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BangLuong.Data.Entities.NhanVien", b =>
                {
                    b.HasOne("BangLuong.Data.Entities.ChucVu", "ChucVu")
                        .WithMany("NhanVien")
                        .HasForeignKey("MaCV");

                    b.HasOne("BangLuong.Data.Entities.PhongBan", "PhongBan")
                        .WithMany("NhanVien")
                        .HasForeignKey("MaPB");

                    b.Navigation("ChucVu");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("BangTinhLuong", b =>
                {
                    b.HasOne("BangLuong.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("BangTinhLuong")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ChamCong", b =>
                {
                    b.HasOne("BangLuong.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("ChamCong")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ChiTietKhenThuong", b =>
                {
                    b.HasOne("DanhMucKhenThuong", "DanhMucKhenThuong")
                        .WithMany("ChiTietKhenThuong")
                        .HasForeignKey("MaKT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BangLuong.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("ChiTietKhenThuong")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucKhenThuong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ChiTietKyLuat", b =>
                {
                    b.HasOne("DanhMucKyLuat", "DanhMucKyLuat")
                        .WithMany("ChiTietKyLuat")
                        .HasForeignKey("MaKL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BangLuong.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("ChiTietKyLuat")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucKyLuat");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("ChiTietPhuCap", b =>
                {
                    b.HasOne("BangLuong.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("ChiTietPhuCap")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DanhMucPhuCap", "DanhMucPhuCap")
                        .WithMany("ChiTietPhuCap")
                        .HasForeignKey("MaPC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMucPhuCap");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NguoiDung", b =>
                {
                    b.HasOne("BangLuong.Data.Entities.NhanVien", "NhanVien")
                        .WithOne("NguoiDung")
                        .HasForeignKey("NguoiDung", "MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NguoiPhuThuoc", b =>
                {
                    b.HasOne("BangLuong.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("NguoiPhuThuoc")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("TongHopCong", b =>
                {
                    b.HasOne("BangLuong.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("TongHopCong")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BangLuong.Data.Entities.ChucVu", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("BangLuong.Data.Entities.NhanVien", b =>
                {
                    b.Navigation("BangTinhLuong");

                    b.Navigation("ChamCong");

                    b.Navigation("ChiTietKhenThuong");

                    b.Navigation("ChiTietKyLuat");

                    b.Navigation("ChiTietPhuCap");

                    b.Navigation("HopDong");

                    b.Navigation("NguoiDung");

                    b.Navigation("NguoiPhuThuoc");

                    b.Navigation("TongHopCong");
                });

            modelBuilder.Entity("BangLuong.Data.Entities.PhongBan", b =>
                {
                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DanhMucKhenThuong", b =>
                {
                    b.Navigation("ChiTietKhenThuong");
                });

            modelBuilder.Entity("DanhMucKyLuat", b =>
                {
                    b.Navigation("ChiTietKyLuat");
                });

            modelBuilder.Entity("DanhMucPhuCap", b =>
                {
                    b.Navigation("ChiTietPhuCap");
                });
#pragma warning restore 612, 618
        }
    }
}
